version: 2.1
orbs:
 slack: circleci/slack@4.0

jobs:
 build:
  docker:
   - image: cimg/node:lts
  steps:
   - checkout
   - run: echo "Pull Request"
   - run: yarn install
   - run: yarn test
   - slack/status:
      success_message: 'OK'
      failure_message: 'NG'
      webhook: '${SLACK_WEBHOOK}'
