version: 2.1
orbs:
  slack: circleci/slack@4.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run echo "OK"
      - slack/notify:
          color: '#42e2f4'
          message: "aaa"
          webhook: {webhook}
      - run:
          command: |
            echo "hello world~"
            exit 1
workflows:
  version: 2
  btd:
    jobs:
    - build 