version: 2.1

jobs:
 build:
  docker:
   - image: cimg/node:lts
  steps:
   - checkout
   - run: echo "Pull Request"
   - run: yarn install
   - run: yarn test
   - slack/notify:
          color: '#42e2f4'
          mentions: 'USERID1,USERID2,'
          message: This is a custom message notification
          webhook: webhook
orbs:
  slack: circleci/slack@4.0.0
version: 2.1
workflows:
  your-workflow:
    jobs:
      - build